language: ruby
cache: bundler
before_script: bundle install
script: bundle exec rake test
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.1
matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 2.0.0
      gemfile: Gemfile_rack_2
    - rvm: 2.1.10
      gemfile: Gemfile_rack_2
gemfile:
  - Gemfile_rack_1
  - Gemfile_rack_2

